import {
  ArrowRight,
  ArrowUp,
  Atom,
  Award,
  BarChart3,
  Bot,
  Boxes,
  Braces,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  Check,
  ChevronDown,
  Cloud,
  Code2,
  Container,
  Cpu,
  Database,
  ExternalLink,
  Facebook,
  FolderKanban,
  Gauge,
  Github,
  GitBranch,
  GraduationCap,
  Instagram,
  Layers3,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  MessageSquareQuote,
  Monitor,
  Network,
  Palette,
  Phone,
  Rocket,
  Send,
  Server,
  ShieldCheck,
  Sparkles,
  Terminal,
  Twitter,
  Wind,
  Workflow,
  X,
  Youtube,
  Zap,
} from 'lucide-react'

export const iconMap = {
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  award: Award,
  brain: BrainCircuit,
  briefcase: BriefcaseBusiness,
  building: Building2,
  chart: BarChart3,
  check: Check,
  cloud: Cloud,
  code: Code2,
  container: Container,
  cpu: Cpu,
  database: Database,
  'external-link': ExternalLink,
  facebook: Facebook,
  folder: FolderKanban,
  gauge: Gauge,
  github: Github,
  'git-branch': GitBranch,
  graduation: GraduationCap,
  instagram: Instagram,
  layers: Layers3,
  linkedin: Linkedin,
  mail: Mail,
  map: MapPin,
  menu: Menu,
  message: MessageSquareQuote,
  monitor: Monitor,
  network: Network,
  palette: Palette,
  phone: Phone,
  react: Atom,
  rocket: Rocket,
  send: Send,
  server: Server,
  shield: ShieldCheck,
  sparkles: Sparkles,
  terminal: Terminal,
  twitter: Twitter,
  workflow: Workflow,
  x: X,
  youtube: Youtube,
  zap: Zap,
  python: Braces,
  javascript: Braces,
  tailwind: Wind,
  postgres: Database,
  vector: Boxes,
  bot: Bot,
  chevron: ChevronDown,
}

export function getIcon(name) {
  return iconMap[name] || Sparkles
}
